# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 超级艺术
email: leo@superarts.org
description: > # this means to ignore newlines until "baseurl:"
  刘日天年轻时代的作品集合
baseurl: "/cn" # the subpath of your site, e.g. /blog
url: "http://www.superarts.org" # the base hostname & protocol for your site
twitter_username: superarts_org
github_username:  superarts

# Build settings
markdown: kramdown